# Form implementation generated from reading ui file 'add_order.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sqlite3

class Ui_add_ord(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(263, 240)
        Form.setStyleSheet("font: 8pt \"MS Gothic\";\n"
"background-color: rgb(212, 212, 212);")
        self.add_btn = QtWidgets.QPushButton(parent=Form)
        self.add_btn.setGeometry(QtCore.QRect(30, 182, 201, 41))
        self.add_btn.setObjectName("add_btn")
        self.dish_add = QtWidgets.QLineEdit(parent=Form)
        self.dish_add.setGeometry(QtCore.QRect(10, 20, 241, 31))
        self.dish_add.setObjectName("dish_add")
        self.stol_num = QtWidgets.QComboBox(parent=Form)
        self.stol_num.setGeometry(QtCore.QRect(10, 80, 241, 31))
        self.stol_num.addItems(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'])
        self.stol_num.setObjectName("stol_num")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.add_btn.clicked.connect(self.add_ord)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Добавление заказа"))
        self.add_btn.setText(_translate("Form", "Добавить"))
        self.dish_add.setPlaceholderText(_translate("Form", "Выберете блюдо..."))
        self.stol_num.setPlaceholderText(_translate("Form", "Введите номер стола"))

    def add_ord(self):
        con = sqlite3.connect('main.db')
        cur = con.cursor()
        cur.execute(f'SELECT * FROM orders WHERE dish_name="{self.dish_add.text()}"'
                    f' and table_num ="{self.stol_num.currentText()}";')
        value = cur.fetchall()

        if value != []:
            error = QtWidgets.QMessageBox()
            error.setWindowTitle('Ошибка!')
            error.setText('Такой заказ уже имеется!')
            error.exec()

        elif value == []:
            cur.execute(f"INSERT INTO orders (dish_name, table_num) VALUES ('{self.dish_add.text()}' ,"
                        f" '{self.stol_num.currentText()}');")
            con.commit()
            con.close
            done = QtWidgets.QMessageBox()
            done.setWindowTitle("Успешно!")
            done.setText('Заказ успешно создан!')
            done.exec()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_add_ord()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())