# Form implementation generated from reading ui file 'add_order.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_add_ord(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(263, 240)
        Form.setStyleSheet("font: 8pt \"MS Gothic\";\n"
"background-color: rgb(212, 212, 212);")
        self.add_btn = QtWidgets.QPushButton(parent=Form)
        self.add_btn.setGeometry(QtCore.QRect(30, 182, 201, 41))
        self.add_btn.setObjectName("add_btn")
        self.dish_add = QtWidgets.QLineEdit(parent=Form)
        self.dish_add.setGeometry(QtCore.QRect(10, 20, 241, 31))
        self.dish_add.setObjectName("dish_add")
        self.stol_num = QtWidgets.QComboBox(parent=Form)
        self.stol_num.setGeometry(QtCore.QRect(10, 80, 241, 31))
        self.stol_num.addItems(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'])
        self.stol_num.setObjectName("stol_num")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Добавление заказа"))
        self.add_btn.setText(_translate("Form", "Добавить"))
        self.dish_add.setPlaceholderText(_translate("Form", "Выберете блюдо..."))
        self.stol_num.setPlaceholderText(_translate("Form", "Введите номер стола"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_add_ord()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())