# Form implementation generated from reading ui file 'admin.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(465, 265)
        Form.setStyleSheet("font: 10pt \"MS Gothic\";\n"
"background-color: rgb(212, 212, 212);")
        self.prodykti = QtWidgets.QPushButton(parent=Form)
        self.prodykti.setGeometry(QtCore.QRect(250, 120, 181, 41))
        self.prodykti.setObjectName("prodykti")
        self.stoli = QtWidgets.QPushButton(parent=Form)
        self.stoli.setGeometry(QtCore.QRect(30, 50, 171, 41))
        self.stoli.setObjectName("stoli")
        self.sotrudniki = QtWidgets.QPushButton(parent=Form)
        self.sotrudniki.setGeometry(QtCore.QRect(250, 50, 181, 41))
        self.sotrudniki.setObjectName("sotrudniki")
        self.klienti = QtWidgets.QPushButton(parent=Form)
        self.klienti.setGeometry(QtCore.QRect(30, 120, 171, 41))
        self.klienti.setObjectName("klienti")
        self.Back_btn = QtWidgets.QPushButton(parent=Form)
        self.Back_btn.setGeometry(QtCore.QRect(140, 200, 181, 41))
        self.Back_btn.setAutoExclusive(False)
        self.Back_btn.setObjectName("Back_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Окно Администратора"))
        self.prodykti.setText(_translate("Form", "Продукты"))
        self.stoli.setText(_translate("Form", "Столы"))
        self.sotrudniki.setText(_translate("Form", "Сотрудники"))
        self.klienti.setText(_translate("Form", "Клиенты"))
        self.Back_btn.setText(_translate("Form", "Назад"))
