# Form implementation generated from reading ui file 'client_win.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtSql import QSqlQueryModel, QSqlDatabase, QSqlQuery

class Ui_Client(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(734, 510)
        Form.setStyleSheet("font: 8pt \"MS Gothic\";\n"
"background-color: rgb(212, 212, 212);")
        self.Client_table = QtWidgets.QTableView(parent=Form)
        self.Client_table.setGeometry(QtCore.QRect(10, 10, 711, 451))
        self.Client_table.setObjectName("Client_table")
        self.add_btn = QtWidgets.QPushButton(parent=Form)
        self.add_btn.setGeometry(QtCore.QRect(10, 480, 171, 23))
        self.add_btn.setObjectName("add_btn")
        self.back = QtWidgets.QPushButton(parent=Form)
        self.back.setGeometry(QtCore.QRect(550, 480, 171, 23))
        self.back.setObjectName("back")

        # вывод таблицы
        db = QSqlDatabase.addDatabase("QSQLITE")
        db.setDatabaseName('main.db')
        db.open()
        query = QSqlQuery()
        query.prepare("SELECT * FROM clients")
        query.exec()

        model = QSqlQueryModel()
        model.setQuery(query)
        self.Client_table.setModel(model)
        self.Client_table.show()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Клиенты"))
        self.add_btn.setText(_translate("Form", "Добавить клиента"))
        self.back.setText(_translate("Form", "Назад"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Client()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())