# Form implementation generated from reading ui file 'Employers_win.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Emp(object):
    def setupUi(self, Form):
        Form.setObjectName("Сотрудники")
        Form.resize(660, 471)
        Form.setStyleSheet("font: 10pt \"MS Gothic\";\n"
                           "background-color: rgb(212, 212, 212);")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(35, 21, 591, 421))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableView = QtWidgets.QTableView(parent=self.widget)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.add_btn = QtWidgets.QPushButton(parent=self.widget)
        self.add_btn.setObjectName("add_btn")
        self.verticalLayout.addWidget(self.add_btn)
        self.back = QtWidgets.QPushButton(parent=self.widget)
        self.back.setObjectName("back")
        self.verticalLayout.addWidget(self.back)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Сотрудники"))
        self.back.setText(_translate("Form", "Назад"))
        self.add_btn.setText(_translate("Form", "Добавить сотрудника"))
