# Form implementation generated from reading ui file 'Employers_win.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import sqlite3
from PyQt6 import QtCore, QtGui, QtWidgets

from PyQt6.QtWidgets import (
    QApplication, QMainWindow, QTableWidget, 
    QTableWidgetItem, QDockWidget, QFormLayout, 
    QLineEdit, QWidget, QPushButton, QSpinBox, 
    QMessageBox, QToolBar, QMessageBox
)

class Ui_Emp(object):
    def setupUi(self, Form):
        Form.setObjectName("Сотрудники")
        Form.resize(660, 471)
        Form.setStyleSheet("font: 10pt \"MS Gothic\";\n"
                           "background-color: rgb(212, 212, 212);")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(35, 21, 591, 421))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableView = QtWidgets.QTableView(parent=self.widget)
        self.tableView.setObjectName("tableView")
        self.tableView.setGeometry(100, 100, 300, 300)
        

        employees = [
            {'First Name': 'John', 'Last Name': 'Doe', 'Age': 25},
            {'First Name': 'Jane', 'Last Name': 'Doe', 'Age': 22},
            {'First Name': 'Alice', 'Last Name': 'Doe', 'Age': 22},
        ]
        con = sqlite3.connect('main.db')
        cur = con.cursor()
        cur.execute(f'SELECT * FROM users;')
        employees = cur.fetchall()
        print(employees)

        self.table = QTableWidget(self)
        self.setCentralWidget(self.table)

        self.table.setColumnCount(5)
        self.table.setColumnWidth(0, 150)
        self.table.setColumnWidth(1, 150)
        self.table.setColumnWidth(2, 50)
        self.table.setColumnWidth(3, 150)
        self.table.setColumnWidth(4, 150)

        #self.table.setHorizontalHeaderLabels(employees[0].keys())
        self.table.setRowCount(len(employees))

        row = 0
        for e in employees:
            self.table.setItem(row, 0, QTableWidgetItem(e[0]))
            self.table.setItem(row, 1, QTableWidgetItem(e[1]))
            self.table.setItem(row, 2, QTableWidgetItem(str(e[2])))
            self.table.setItem(row, 3, QTableWidgetItem(e[3]))
            self.table.setItem(row, 4, QTableWidgetItem(e[4]))
            row += 1
        '''        con = sqlite3.connect('main.db')
        cur = con.cursor()
        cur.execute(f'SELECT * FROM users WHERE username="{self.reg_line.text()}";')
        value = cur.fetchall()
        '''
        self.verticalLayout.addWidget(self.tableView)
        self.add_btn = QtWidgets.QPushButton(parent=self.widget)
        self.add_btn.setObjectName("add_btn")
        self.verticalLayout.addWidget(self.add_btn)
        self.back = QtWidgets.QPushButton(parent=self.widget)
        self.back.setObjectName("back")
        self.verticalLayout.addWidget(self.back)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Сотрудники"))
        self.back.setText(_translate("Form", "Назад"))
        self.add_btn.setText(_translate("Form", "Добавить сотрудника"))
