# Form implementation generated from reading ui file 'Employers_win.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import sqlite3
import sys
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtSql import QSqlQueryModel, QSqlDatabase, QSqlQuery


from windows.add_emp import Ui_add_emp

class Ui_Emp(object):
    def setupUi(self, Form):
        Form.setObjectName("Сотрудники")
        Form.resize(660, 471)
        Form.setStyleSheet("font: 10pt \"MS Gothic\";\n"
                           "background-color: rgb(212, 212, 212);")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(35, 21, 591, 421))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableView = QtWidgets.QTableView(parent=self.widget)
        self.tableView.setObjectName("tableView")
        self.tableView.setGeometry(100, 100, 300, 300)
        self.verticalLayout.addWidget(self.tableView)
        self.add_btn = QtWidgets.QPushButton(parent=self.widget)
        self.add_btn.setObjectName("add_btn")
        self.verticalLayout.addWidget(self.add_btn)
        self.back = QtWidgets.QPushButton(parent=self.widget)
        self.back.setObjectName("back")
        self.verticalLayout.addWidget(self.back)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        #вывод таблицы
        db = QSqlDatabase.addDatabase("QSQLITE")
        db.setDatabaseName('main.db')
        db.open()
        query = QSqlQuery()
        query.prepare("SELECT * FROM employees")
        query.exec()

        model = QSqlQueryModel()
        model.setQuery(query)
        self.tableView.setModel(model)
        self.tableView.show()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Сотрудники"))
        self.back.setText(_translate("Form", "Назад"))
        self.add_btn.setText(_translate("Form", "Добавить сотрудника"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Emp()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())