# Form implementation generated from reading ui file 'menu_win.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Menu(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setStyleSheet("font: 10pt \"MS Gothic\";\n"
                           "background-color: rgb(212, 212, 212);")
        self.back_btn = QtWidgets.QPushButton(parent=Form)
        self.back_btn.setGeometry(QtCore.QRect(230, 400, 191, 41))
        self.back_btn.setObjectName("back_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.back_btn.setText(_translate("Form", "PushButton"))
