# Form implementation generated from reading ui file 'oficiant.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form_of(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(454, 271)
        Form.setStyleSheet("font: 10pt \"MS Gothic\";\n"
"background-color: rgb(212, 212, 212);")
        self.pushButton_3 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_3.setGeometry(QtCore.QRect(240, 60, 181, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_4.setGeometry(QtCore.QRect(140, 120, 171, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_5.setGeometry(QtCore.QRect(140, 200, 171, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 60, 171, 41))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Официант"))
        self.pushButton_3.setText(_translate("Form", "Меню"))
        self.pushButton_4.setText(_translate("Form", "Заказы"))
        self.pushButton_5.setText(_translate("Form", "Назад"))
        self.pushButton_2.setText(_translate("Form", "Столы"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form_of()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
