# Form implementation generated from reading ui file 'registr.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(400, 325)
        widget.setStyleSheet("font: 8pt \"MS Gothic\";\n"
"background-color: rgb(212, 212, 212);")
        self.reg_btn = QtWidgets.QPushButton(parent=widget)
        self.reg_btn.setGeometry(QtCore.QRect(100, 270, 201, 41))
        self.reg_btn.setStyleSheet("font: 8pt \"MS Gothic\";\n"
"")
        self.reg_btn.setObjectName("reg_btn")
        self.reg_line = QtWidgets.QLineEdit(parent=widget)
        self.reg_line.setGeometry(QtCore.QRect(80, 30, 241, 31))
        self.reg_line.setObjectName("reg_line")
        self.pass_line = QtWidgets.QLineEdit(parent=widget)
        self.pass_line.setGeometry(QtCore.QRect(80, 90, 241, 31))
        self.pass_line.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.pass_line.setObjectName("pass_line")
        self.emai_line = QtWidgets.QLineEdit(parent=widget)
        self.emai_line.setGeometry(QtCore.QRect(80, 150, 241, 31))
        self.emai_line.setObjectName("emai_line")
        self.combobox2 = QtWidgets.QComboBox(parent=widget)
        self.combobox2.setGeometry(QtCore.QRect(80, 210, 241, 31))
        self.combobox2.addItems(['admin', 'aaiter'])
        self.combobox2.setObjectName("combobox2")




        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Регистрация"))
        self.reg_btn.setText(_translate("widget", "Зарегистрироваться"))
        self.reg_line.setPlaceholderText(_translate("widget", "Username..."))
        self.pass_line.setPlaceholderText(_translate("widget", "Password..."))
        self.emai_line.setPlaceholderText(_translate("widget", "Email..."))
        #self.lineEdit.setPlaceholderText(_translate("widget", "Role..."))
        self.combobox2.setPlaceholderText(_translate("widget",'Role...'))
        self.combobox2.setCurrentIndex(-1)
