# Form implementation generated from reading ui file 'vhod.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_Main(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(352, 331)
        Form.setStyleSheet("font: 8pt \"MS Gothic\";\n"
"background-color: rgb(212, 212, 212);")
        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit.setGeometry(QtCore.QRect(40, 40, 271, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 100, 271, 31))
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(70, 280, 211, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 230, 211, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.combobox2 = QtWidgets.QComboBox(parent=Form)
        self.combobox2.setGeometry(QtCore.QRect(40, 160, 271, 31))
        self.combobox2.addItems(['admin', 'waiter'])
        self.combobox2.setObjectName("combobox2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Авторизация"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Login..."))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Password..."))
        self.pushButton.setText(_translate("Form", "Sign up"))
        self.pushButton_2.setText(_translate("Form", "Sign in"))
        self.combobox2.setPlaceholderText('Role...')
        self.combobox2.setCurrentIndex(-1)